#  
#  To use this DEPS file to re-create a Chromium release you
#  need the tools from http://dev.chromium.org installed.
#  
#  This DEPS file corresponds to Chromium 14.0.835.116
#  
#  
#  
deps_os = {
   'win': {
      'src/chrome_frame/tools/test/reference_build/chrome_win':
         '/trunk/deps/reference_builds/chrome_win@89574',
      'src/third_party/yasm/binaries':
         '/trunk/deps/third_party/yasm/binaries@74228',
      'src/chrome/tools/test/reference_build/chrome_win':
         '/trunk/deps/reference_builds/chrome_win@89574',
      'src/third_party/cygwin':
         '/trunk/deps/third_party/cygwin@66844',
      'src/third_party/python_26':
         '/trunk/tools/third_party/python_26@89111',
      'src/third_party/swig/win':
         '/trunk/deps/third_party/swig/win@69281',
      'src/third_party/xulrunner-sdk':
         '/trunk/deps/third_party/xulrunner-sdk@71609',
      'src/third_party/ffmpeg/binaries/chromium/win/ia32':
         '/branches/ffmpeg/835/binaries/win@98087',
      'src/third_party/pefile':
         'http://pefile.googlecode.com/svn/trunk@63',
      'src/third_party/lighttpd':
         '/trunk/deps/third_party/lighttpd@33727',
      'src/third_party/psyco_win32':
         '/trunk/deps/third_party/psyco_win32@79861',
      'src/third_party/mingw-w64/mingw/bin':
         'http://src.chromium.org/native_client/trunk/src/third_party/mingw-w64/mingw/bin@5360',
      'src/third_party/nss':
         '/trunk/deps/third_party/nss@93459',
      'src/rlz':
         'http://rlz.googlecode.com/svn/trunk@44',
   },
   'mac': {
      'src/third_party/WebKit/WebKitLibraries':
         'http://svn.webkit.org/repository/webkit/branches/chromium/835/WebKitLibraries@93828',
      'src/third_party/GTM':
         'http://google-toolbox-for-mac.googlecode.com/svn/trunk@459',
      'src/third_party/pdfsqueeze':
         'http://pdfsqueeze.googlecode.com/svn/trunk@4',
      'src/chrome/installer/mac/third_party/xz/xz':
         '/trunk/deps/third_party/xz@87706',
      'src/third_party/swig/mac':
         '/trunk/deps/third_party/swig/mac@69281',
      'src/chrome/tools/test/reference_build/chrome_mac':
         '/trunk/deps/reference_builds/chrome_mac@89574',
      'src/third_party/lighttpd':
         '/trunk/deps/third_party/lighttpd@33737',
      'src/third_party/nss':
         '/trunk/deps/third_party/nss@90649',
   },
   'unix': {
      'src/third_party/xdg-utils':
         '/trunk/deps/third_party/xdg-utils@93299',
      'src/third_party/openssl':
         '/trunk/deps/third_party/openssl@93618',
      'src/third_party/swig/linux':
         '/trunk/deps/third_party/swig/linux@69281',
      'src/third_party/cros':
         'http://git.chromium.org/git/cros.git@56c93050',
      'src/third_party/WebKit/Tools/gdb':
         'http://svn.webkit.org/repository/webkit/branches/chromium/835/Tools/gdb@93828',
      'src/third_party/lss':
         'http://linux-syscall-support.googlecode.com/svn/trunk/lss@3',
      'src/chrome/tools/test/reference_build/chrome_linux':
         '/trunk/deps/reference_builds/chrome_linux@89574',
   },
}

deps = {
   'src/native_client':
      'http://src.chromium.org/native_client/branches/835/src/native_client@6481',
   'src/third_party/skia/include':
      'http://skia.googlecode.com/svn/branches/chrome/835/trunk/include@2158',
   'src/third_party/flac':
      '/trunk/deps/third_party/flac@75901',
   'src/chrome/test/data/layout_tests/LayoutTests/fast/workers':
      'http://svn.webkit.org/repository/webkit/branches/chromium/835/LayoutTests/fast/workers@93828',
   'src/chrome/test/data/layout_tests/LayoutTests/http/tests/xmlhttprequest':
      'http://svn.webkit.org/repository/webkit/branches/chromium/835/LayoutTests/http/tests/xmlhttprequest@93828',
   'src/third_party/sfntly/src/sfntly':
      'http://sfntly.googlecode.com/svn/trunk/cpp/src/sfntly@20',
   'src/chrome/test/data/layout_tests/LayoutTests/platform/chromium/fast/workers':
      'http://svn.webkit.org/repository/webkit/branches/chromium/835/LayoutTests/platform/chromium/fast/workers@93828',
   'src/third_party/webdriver/python/selenium/test':
      'http://selenium.googlecode.com/svn/trunk/py/test@12107',
   'src/chrome/test/data/layout_tests/LayoutTests/fast/js/resources':
      'http://svn.webkit.org/repository/webkit/branches/chromium/835/LayoutTests/fast/js/resources@93828',
   'src/chrome/test/data/layout_tests/LayoutTests/platform/chromium-mac/http/tests/workers':
      'http://svn.webkit.org/repository/webkit/branches/chromium/835/LayoutTests/platform/chromium-mac/http/tests/workers@93828',
   'src/chrome/test/data/layout_tests/LayoutTests/http/tests/resources':
      'http://svn.webkit.org/repository/webkit/branches/chromium/835/LayoutTests/http/tests/resources@93828',
   'src/third_party/skia/gpu':
      'http://skia.googlecode.com/svn/branches/chrome/835/trunk/gpu@2156',
   'src/chrome/test/data/layout_tests/LayoutTests/http/tests/filesystem':
      'http://svn.webkit.org/repository/webkit/branches/chromium/835/LayoutTests/http/tests/filesystem@93828',
   'src/third_party/safe_browsing/testing':
      'http://google-safe-browsing.googlecode.com/svn/trunk/testing@106',
   'src/third_party/pyftpdlib/src':
      'http://pyftpdlib.googlecode.com/svn/trunk@888',
   'src/third_party/WebKit':
      '/trunk/deps/third_party/WebKit@76115',
   'src/chrome/test/data/layout_tests/LayoutTests/fast/events':
      'http://svn.webkit.org/repository/webkit/branches/chromium/835/LayoutTests/fast/events@93828',
   'src/third_party/bidichecker':
      'http://bidichecker.googlecode.com/svn/trunk/lib@4',
   'src/third_party/ots':
      'http://ots.googlecode.com/svn/trunk@69',
   'src/third_party/WebKit/Source':
      'http://svn.webkit.org/repository/webkit/branches/chromium/835/Source@93828',
   'src/chrome/test/data/layout_tests/LayoutTests/http/tests/workers':
      'http://svn.webkit.org/repository/webkit/branches/chromium/835/LayoutTests/http/tests/workers@93828',
   'src/testing/gmock':
      'http://googlemock.googlecode.com/svn/trunk@374',
   'src/chrome/test/data/extensions/api_test/permissions/nacl_enabled/bin':
      'http://src.chromium.org/native_client/trunk/src/native_client/tests/prebuilt@6201',
   'src/chrome/test/data/layout_tests/LayoutTests/fast/filesystem/workers':
      'http://svn.webkit.org/repository/webkit/branches/chromium/835/LayoutTests/fast/filesystem/workers@93828',
   'src/tools/gyp':
      'http://gyp.googlecode.com/svn/trunk@983',
   'src/sdch/open-vcdiff':
      'http://open-vcdiff.googlecode.com/svn/trunk@28',
   'src/chrome/test/data/layout_tests/LayoutTests/platform/chromium-win/storage/domstorage':
      'http://svn.webkit.org/repository/webkit/branches/chromium/835/LayoutTests/platform/chromium-win/storage/domstorage@93828',
   'src/tools/page_cycler/acid3':
      '/trunk/deps/page_cycler/acid3@19546',
   'src/chrome/test/data/layout_tests/LayoutTests/fast/filesystem/resources':
      'http://svn.webkit.org/repository/webkit/branches/chromium/835/LayoutTests/fast/filesystem/resources@93828',
   'src/build/util/support':
      '/trunk/deps/support@20411',
   'src/third_party/libjingle/source':
      'http://libjingle.googlecode.com/svn/trunk@77',
   'src':
      '/branches/835/src@98401',
   'src/third_party/WebKit/Tools/DumpRenderTree':
      'http://svn.webkit.org/repository/webkit/branches/chromium/835/Tools/DumpRenderTree@93828',
   'src/third_party/hunspell':
      '/trunk/deps/third_party/hunspell@93061',
   'src/chrome/test/data/layout_tests/LayoutTests/http/tests/appcache':
      'http://svn.webkit.org/repository/webkit/branches/chromium/835/LayoutTests/http/tests/appcache@93828',
   'src/testing/gtest':
      'http://googletest.googlecode.com/svn/trunk@560',
   'src/v8':
      'http://v8.googlecode.com/svn/branches/3.4@9022',
   'src/third_party/libvpx':
      '/branches/libvpx/835@98054',
   'src/third_party/skia/third_party/glu':
      'http://skia.googlecode.com/svn/branches/chrome/835/trunk/third_party/glu@2156',
   'src/breakpad/src':
      'http://google-breakpad.googlecode.com/svn/trunk/src@786',
   'chromeos':
      '/trunk/src/tools/cros.DEPS@94063',
   'src/chrome/test/data/perf/frame_rate/content':
      '/trunk/deps/frame_rate/content@93671',
   'src/googleurl':
      'http://google-url.googlecode.com/svn/trunk@159',
   'src/third_party/webgl_conformance':
      '/trunk/deps/third_party/webgl/sdk/tests@93490',
   'src/third_party/hunspell_dictionaries':
      '/trunk/deps/third_party/hunspell_dictionaries@79099',
   'src/chrome/test/data/layout_tests/LayoutTests/platform/chromium-win/fast/events':
      'http://svn.webkit.org/repository/webkit/branches/chromium/835/LayoutTests/platform/chromium-win/fast/events@93828',
   'src/third_party/leveldb':
      'http://leveldb.googlecode.com/svn/trunk@36',
   'src/third_party/scons-2.0.1':
      'http://src.chromium.org/native_client/trunk/src/third_party/scons-2.0.1@5360',
   'src/third_party/webdriver/python/selenium':
      'http://selenium.googlecode.com/svn/trunk/py/selenium@12107',
   'src/third_party/pylib':
      'http://src.chromium.org/native_client/trunk/src/third_party/pylib@5360',
   'src/third_party/WebKit/LayoutTests':
      'http://svn.webkit.org/repository/webkit/branches/chromium/835/LayoutTests@93828',
   'src/third_party/snappy/src':
      'http://snappy.googlecode.com/svn/trunk@37',
   'src/chrome/test/data/layout_tests/LayoutTests/http/tests/websocket/tests':
      'http://svn.webkit.org/repository/webkit/branches/chromium/835/LayoutTests/http/tests/websocket/tests@93828',
   'src/third_party/webrtc':
      'http://webrtc.googlecode.com/svn/trunk/src@232',
   'src/chrome/test/data/layout_tests/LayoutTests/media':
      'http://svn.webkit.org/repository/webkit/branches/chromium/835/LayoutTests/media@93828',
   'src/chrome/test/data/layout_tests/LayoutTests/platform/chromium-mac/fast/events':
      'http://svn.webkit.org/repository/webkit/branches/chromium/835/LayoutTests/platform/chromium-mac/fast/events@93828',
   'src/third_party/libjpeg_turbo':
      '/trunk/deps/third_party/libjpeg_turbo@83675',
   'src/chrome/test/data/layout_tests/LayoutTests/platform/chromium-mac/storage/domstorage':
      'http://svn.webkit.org/repository/webkit/branches/chromium/835/LayoutTests/platform/chromium-mac/storage/domstorage@93828',
   'src/third_party/skia/src':
      'http://skia.googlecode.com/svn/branches/chrome/835/trunk/src@2158',
   'src/third_party/ffmpeg':
      '/branches/ffmpeg/835/source@98075',
   'src/third_party/cacheinvalidation/files/src/google':
      'http://google-cache-invalidation-api.googlecode.com/svn/trunk/src/google@135',
   'src/native_client/src/third_party/ppapi':
      '/trunk/src/ppapi@93797',
   'src/chrome/test/data/layout_tests/LayoutTests/platform/chromium-win/fast/workers':
      'http://svn.webkit.org/repository/webkit/branches/chromium/835/LayoutTests/platform/chromium-win/fast/workers@93828',
   'src/third_party/WebKit/Tools/Scripts':
      'http://svn.webkit.org/repository/webkit/branches/chromium/835/Tools/Scripts@93828',
   'src/chrome/test/data/layout_tests/LayoutTests/storage/domstorage':
      'http://svn.webkit.org/repository/webkit/branches/chromium/835/LayoutTests/storage/domstorage@93828',
   'src/third_party/icu':
      '/trunk/deps/third_party/icu46@93875',
   'src/third_party/speex':
      '/trunk/deps/third_party/speex@83190',
   'src/seccompsandbox':
      'http://seccompsandbox.googlecode.com/svn/trunk@160',
   'src/third_party/yasm/source/patched-yasm':
      '/trunk/deps/third_party/yasm/patched-yasm@73761',
   'src/chrome/test/data/layout_tests/LayoutTests/platform/chromium-win/http/tests/workers':
      'http://svn.webkit.org/repository/webkit/branches/chromium/835/LayoutTests/platform/chromium-win/http/tests/workers@93828',
   'src/third_party/angle':
      'http://angleproject.googlecode.com/svn/branches/chrome_m14@732',
   'src/third_party/swig/Lib':
      '/trunk/deps/third_party/swig/Lib@69281',
}

skip_child_includes =  ['breakpad', 'chrome_frame', 'native_client', 'o3d', 'pdf', 'sdch', 'skia', 'testing', 'third_party', 'v8'] 

hooks =  [{'action': ['python', 'src/build/gyp_chromium'], 'pattern': '.'}, {'action': ['python', 'src/build/download_nacl_irt.py', '--base_url', 'http://commondatastorage.googleapis.com/nativeclient-archive2/irt/branches/m14', '--nacl_revision', '6297', '--file_hash', 'x86_32', '02c4c8443656cf202562a2b9c9a63f3231fa1fbb', '--file_hash', 'x86_64', 'caa69972df32882635a78f9212ea1d759380ab51'], 'pattern': '.'}] 

include_rules =  ['+base', '+build', '+ipc', '+unicode', '+testing']