#  
#  To use this DEPS file to re-create a Chromium release you
#  need the tools from http://dev.chromium.org installed.
#  
#  This DEPS file corresponds to Chromium 7.0.517.22
#  
#  
#  
deps_os = {
   'win': {
      'src/third_party/xulrunner-sdk':
         '/trunk/deps/third_party/xulrunner-sdk@17887',
      'src/chrome_frame/tools/test/reference_build/chrome':
         '/trunk/deps/reference_builds/chrome@51194',
      'src/third_party/cygwin':
         '/trunk/deps/third_party/cygwin@11984',
      'src/third_party/python_24':
         '/trunk/deps/third_party/python_24@22967',
      'src/third_party/swig/win':
         '/trunk/deps/third_party/swig/win@40423',
      'src/third_party/ffmpeg/binaries/chromium/win/ia32':
         '/trunk/deps/third_party/ffmpeg/binaries/win@58574',
      'src/third_party/lighttpd':
         '/trunk/deps/third_party/lighttpd@33727',
      'src/third_party/pefile':
         'http://pefile.googlecode.com/svn/trunk@63',
      'src/chrome/tools/test/reference_build/chrome':
         '/trunk/deps/reference_builds/chrome@41984',
      'src/third_party/nss':
         '/trunk/deps/third_party/nss@55513',
      'src/third_party/mingw-w64/mingw/bin':
         'http://src.chromium.org/native_client/trunk/src/third_party/mingw-w64/mingw/bin@3186',
      'src/rlz':
         'http://rlz.googlecode.com/svn/trunk@17',
   },
   'mac': {
      'src/third_party/GTM':
         'http://google-toolbox-for-mac.googlecode.com/svn/trunk@375',
      'src/third_party/pdfsqueeze':
         'http://pdfsqueeze.googlecode.com/svn/trunk@2',
      'src/chrome/installer/mac/third_party/xz/xz':
         '/trunk/deps/third_party/xz@50504',
      'src/third_party/WebKit/WebKitLibraries':
         'http://svn.webkit.org/repository/webkit/branches/chromium/517/WebKitLibraries@66913',
      'src/third_party/yasm/source/patched-yasm':
         '/trunk/deps/third_party/yasm/patched-yasm@50870',
      'src/third_party/WebKit/WebKit/mac':
         'http://svn.webkit.org/repository/webkit/branches/chromium/517/WebKit/mac@66913',
      'src/third_party/swig/mac':
         '/trunk/deps/third_party/swig/mac@40423',
      'src/third_party/lighttpd':
         '/trunk/deps/third_party/lighttpd@33737',
      'src/chrome/tools/test/reference_build/chrome_mac':
         '/trunk/deps/reference_builds/chrome_mac@41963',
      'src/third_party/nss':
         '/trunk/deps/third_party/nss@55513',
   },
   'unix': {
      'src/third_party/swig/linux':
         '/trunk/deps/third_party/swig/linux@40423',
      'src/third_party/cros':
         'http://src.chromium.org/git/cros.git@b6fc7838',
      'src/third_party/yasm/source/patched-yasm':
         '/trunk/deps/third_party/yasm/patched-yasm@50870',
      'src/third_party/xdg-utils':
         '/trunk/deps/third_party/xdg-utils@58316',
      'src/chrome/tools/test/reference_build/chrome_linux':
         '/trunk/deps/reference_builds/chrome_linux@41515',
   },
}

deps = {
   'src/third_party/skia/include':
      'http://skia.googlecode.com/svn/trunk/include@593',
   'src/third_party/WebKit/WebCore':
      'http://svn.webkit.org/repository/webkit/branches/chromium/517/WebCore@68305',
   'src/chrome/test/data/layout_tests/LayoutTests/fast/workers':
      'http://svn.webkit.org/repository/webkit/branches/chromium/517/LayoutTests/fast/workers@66913',
   'src/chrome/test/data/layout_tests/LayoutTests/platform/chromium/fast/workers':
      'http://svn.webkit.org/repository/webkit/branches/chromium/517/LayoutTests/platform/chromium/fast/workers@66913',
   'src/chrome/test/data/layout_tests/LayoutTests/fast/js/resources':
      'http://svn.webkit.org/repository/webkit/branches/chromium/517/LayoutTests/fast/js/resources@66913',
   'src/chrome/test/data/layout_tests/LayoutTests/platform/chromium-mac/http/tests/workers':
      'http://svn.webkit.org/repository/webkit/branches/chromium/517/LayoutTests/platform/chromium-mac/http/tests/workers@66913',
   'src/chrome/test/data/layout_tests/LayoutTests/http/tests/resources':
      'http://svn.webkit.org/repository/webkit/branches/chromium/517/LayoutTests/http/tests/resources@66913',
   'src/chrome/test/data/layout_tests/LayoutTests/storage/domstorage':
      'http://svn.webkit.org/repository/webkit/branches/chromium/517/LayoutTests/storage/domstorage@66913',
   'src/third_party/pcre':
      'http://sawbuck.googlecode.com/svn/trunk/third_party/pcre@102',
   'src/third_party/ppapi':
      'http://ppapi.googlecode.com/svn/trunk@234',
   'src/chrome/test/data/layout_tests/LayoutTests/fast/events':
      'http://svn.webkit.org/repository/webkit/branches/chromium/517/LayoutTests/fast/events@68305',
   'src/third_party/WebKit':
      '/trunk/deps/third_party/WebKit@33467',
   'src/third_party/ots':
      'http://ots.googlecode.com/svn/trunk@35',
   'src/third_party/libvpx/include':
      '/trunk/deps/third_party/libvpx/include@58584',
   'src/chrome/test/data/layout_tests/LayoutTests/http/tests/workers':
      'http://svn.webkit.org/repository/webkit/branches/chromium/517/LayoutTests/http/tests/workers@66913',
   'src/chrome/test/data/extensions/api_test/permissions/nacl_enabled/bin':
      'http://nativeclient.googlecode.com/svn/trunk/src/native_client/tests/prebuilt@3186',
   'src/chrome/test/data/layout_tests/LayoutTests/http/tests/xmlhttprequest':
      'http://svn.webkit.org/repository/webkit/branches/chromium/517/LayoutTests/http/tests/xmlhttprequest@66913',
   'src/tools/gyp':
      'http://gyp.googlecode.com/svn/trunk@840',
   'src/sdch/open-vcdiff':
      'http://open-vcdiff.googlecode.com/svn/trunk@28',
   'src/chrome/test/data/layout_tests/LayoutTests/platform/chromium-win/storage/domstorage':
      'http://svn.webkit.org/repository/webkit/branches/chromium/517/LayoutTests/platform/chromium-win/storage/domstorage@66913',
   'src/tools/page_cycler/acid3':
      '/trunk/deps/page_cycler/acid3@19546',
   'src/third_party/py/simplejson':
      'http://simplejson.googlecode.com/svn/trunk/simplejson@217',
   'src/build/util/support':
      '/trunk/deps/support@60612',
   'src/third_party/cacheinvalidation/files':
      'http://google-cache-invalidation-api.googlecode.com/svn/trunk@35',
   'src/third_party/libjingle/source':
      'http://libjingle.googlecode.com/svn/branches/nextsnap@27',
   'src':
      '/branches/517/src@60601',
   'src/third_party/hunspell':
      '/trunk/deps/third_party/hunspell@51690',
   'src/chrome/test/data/layout_tests/LayoutTests/http/tests/appcache':
      'http://svn.webkit.org/repository/webkit/branches/chromium/517/LayoutTests/http/tests/appcache@66913',
   'src/testing/gtest':
      'http://googletest.googlecode.com/svn/trunk@408',
   'src/v8':
      'http://v8.googlecode.com/svn/branches/2.3@5522',
   'src/breakpad/src':
      'http://google-breakpad.googlecode.com/svn/trunk/src@657',
   'chromeos':
      '/trunk/cros_deps@58658',
   'src/googleurl':
      'http://google-url.googlecode.com/svn/trunk@145',
   'src/third_party/protobuf2/src':
      'http://protobuf.googlecode.com/svn/trunk@327',
   'src/third_party/hunspell_dictionaries':
      '/trunk/deps/third_party/hunspell_dictionaries@51875',
   'src/chrome/test/data/layout_tests/LayoutTests/platform/chromium-win/fast/events':
      'http://svn.webkit.org/repository/webkit/branches/chromium/517/LayoutTests/platform/chromium-win/fast/events@66913',
   'src/third_party/WebKit/JavaScriptCore':
      'http://svn.webkit.org/repository/webkit/branches/chromium/517/JavaScriptCore@67410',
   'src/third_party/sawbuck':
      'http://sawbuck.googlecode.com/svn/trunk/sawbuck@102',
   'src/third_party/libvpx/lib':
      '/trunk/deps/third_party/libvpx/lib@58584',
   'src/third_party/WebKit/LayoutTests':
      'http://svn.webkit.org/repository/webkit/branches/chromium/517/LayoutTests@68305',
   'src/chrome/test/data/layout_tests/LayoutTests/media':
      'http://svn.webkit.org/repository/webkit/branches/chromium/517/LayoutTests/media@66913',
   'src/chrome/test/data/layout_tests/LayoutTests/platform/chromium-mac/fast/events':
      'http://svn.webkit.org/repository/webkit/branches/chromium/517/LayoutTests/platform/chromium-mac/fast/events@66913',
   'src/native_client':
      'http://src.chromium.org/native_client/trunk/src/native_client@3186',
   'src/chrome/test/data/layout_tests/LayoutTests/platform/chromium-mac/storage/domstorage':
      'http://svn.webkit.org/repository/webkit/branches/chromium/517/LayoutTests/platform/chromium-mac/storage/domstorage@66913',
   'src/third_party/WebKit/WebKit/chromium':
      'http://svn.webkit.org/repository/webkit/branches/chromium/517/WebKit/chromium@68290',
   'src/chrome/test/data/layout_tests/LayoutTests/websocket/tests/workers':
      'http://svn.webkit.org/repository/webkit/branches/chromium/517/LayoutTests/websocket/tests/workers@66913',
   'src/third_party/skia/src':
      'http://skia.googlecode.com/svn/trunk/src@593',
   'src/third_party/WebKit/WebKitTools/Scripts':
      'http://svn.webkit.org/repository/webkit/branches/chromium/517/WebKitTools/Scripts@66913',
   'src/third_party/ffmpeg':
      '/trunk/deps/third_party/ffmpeg/source@58574',
   'src/third_party/speex':
      '/trunk/deps/third_party/speex@56515',
   'src/chrome/test/data/layout_tests/LayoutTests/platform/chromium-win/fast/workers':
      'http://svn.webkit.org/repository/webkit/branches/chromium/517/LayoutTests/platform/chromium-win/fast/workers@66913',
   'src/third_party/WebKit/WebKitTools/DumpRenderTree':
      'http://svn.webkit.org/repository/webkit/branches/chromium/517/WebKitTools/DumpRenderTree@66913',
   'src/third_party/icu':
      '/trunk/deps/third_party/icu42@58904',
   'src/seccompsandbox':
      'http://seccompsandbox.googlecode.com/svn/trunk@91',
   'src/chrome/test/data/layout_tests/LayoutTests/platform/chromium-win/http/tests/workers':
      'http://svn.webkit.org/repository/webkit/branches/chromium/517/LayoutTests/platform/chromium-win/http/tests/workers@66913',
   'src/third_party/angle':
      'http://angleproject.googlecode.com/svn/trunk@402',
   'src/third_party/swig/Lib':
      '/trunk/deps/third_party/swig/Lib@40423',
}

skip_child_includes =  ['breakpad', 'chrome_frame', 'gears', 'native_client', 'o3d', 'sdch', 'skia', 'testing', 'third_party', 'v8'] 

hooks =  [{'action': ['python', 'src/build/gyp_chromium'], 'pattern': '.'}] 

include_rules =  ['+base', '+build', '+ipc', '+rlz', '+unicode', '+testing']