#  
#  To use this DEPS file to re-create a Chromium release you
#  need the tools from http://dev.chromium.org installed.
#  
#  This DEPS file corresponds to Chromium 12.0.742.131
#  
#  
#  
deps_os = {
   'win': {
      'src/third_party/yasm/binaries':
         '/trunk/deps/third_party/yasm/binaries@74228',
      'src/third_party/pefile':
         'http://pefile.googlecode.com/svn/trunk@63',
      'src/third_party/swig/win':
         '/trunk/deps/third_party/swig/win@69281',
      'src/third_party/lighttpd':
         '/trunk/deps/third_party/lighttpd@33727',
      'src/chrome/tools/test/reference_build/chrome':
         '/trunk/deps/reference_builds/chrome@70122',
      'src/chrome_frame/tools/test/reference_build/chrome':
         '/trunk/deps/reference_builds/chrome@70122',
      'src/rlz':
         'http://rlz.googlecode.com/svn/trunk@33',
      'src/third_party/ffmpeg/binaries/chromium/win/ia32':
         '/branches/ffmpeg/742/binaries/win@83859',
      'src/third_party/psyco_win32':
         '/trunk/deps/third_party/psyco_win32@79861',
      'src/third_party/mingw-w64/mingw/bin':
         'http://src.chromium.org/native_client/branches/742/src/third_party/mingw-w64/mingw/bin@5042',
      'src/third_party/xulrunner-sdk':
         '/trunk/deps/third_party/xulrunner-sdk@71609',
      'src/third_party/cygwin':
         '/trunk/deps/third_party/cygwin@66844',
      'src/third_party/python_26':
         '/trunk/tools/third_party/python_26@70627',
      'src/third_party/nss':
         '/trunk/deps/third_party/nss@81009',
   },
   'mac': {
      'src/third_party/WebKit/WebKitLibraries':
         'http://svn.webkit.org/repository/webkit/branches/chromium/742/WebKitLibraries@89068',
      'src/third_party/GTM':
         'http://google-toolbox-for-mac.googlecode.com/svn/trunk@440',
      'src/third_party/pdfsqueeze':
         'http://pdfsqueeze.googlecode.com/svn/trunk@4',
      'src/chrome/installer/mac/third_party/xz/xz':
         '/trunk/deps/third_party/xz@50504',
      'src/third_party/swig/mac':
         '/trunk/deps/third_party/swig/mac@69281',
      'src/chrome/tools/test/reference_build/chrome_mac':
         '/trunk/deps/reference_builds/chrome_mac@71120',
      'src/third_party/lighttpd':
         '/trunk/deps/third_party/lighttpd@33737',
      'src/third_party/nss':
         '/trunk/deps/third_party/nss@81009',
   },
   'unix': {
      'src/third_party/xdg-utils':
         '/trunk/deps/third_party/xdg-utils@84156',
      'src/third_party/openssl':
         '/trunk/deps/third_party/openssl@69192',
      'src/third_party/swig/linux':
         '/trunk/deps/third_party/swig/linux@69281',
      'src/third_party/cros':
         'http://git.chromium.org/git/cros.git@c53083dc',
      'src/third_party/WebKit/Tools/gdb':
         'http://svn.webkit.org/repository/webkit/branches/chromium/742/Tools/gdb@89068',
      'src/third_party/lss':
         'http://linux-syscall-support.googlecode.com/svn/trunk/lss@3',
      'src/chrome/tools/test/reference_build/chrome_linux':
         '/trunk/deps/reference_builds/chrome_linux@70120',
   },
}

deps = {
   'src/native_client':
      'http://src.chromium.org/native_client/branches/742/src/native_client@5107',
   'src/third_party/skia/include':
      '/branches/skia/742/include@85752',
   'src/third_party/flac':
      '/trunk/deps/third_party/flac@75901',
   'src/chrome/test/data/layout_tests/LayoutTests/fast/workers':
      'http://svn.webkit.org/repository/webkit/branches/chromium/742/LayoutTests/fast/workers@89068',
   'src/chrome/test/data/layout_tests/LayoutTests/http/tests/xmlhttprequest':
      'http://svn.webkit.org/repository/webkit/branches/chromium/742/LayoutTests/http/tests/xmlhttprequest@89068',
   'src/chrome/test/data/layout_tests/LayoutTests/platform/chromium/fast/workers':
      'http://svn.webkit.org/repository/webkit/branches/chromium/742/LayoutTests/platform/chromium/fast/workers@89068',
   'src/third_party/webdriver/python/selenium/test':
      'http://selenium.googlecode.com/svn/trunk/py/test@11696',
   'src/chrome/test/data/layout_tests/LayoutTests/fast/js/resources':
      'http://svn.webkit.org/repository/webkit/branches/chromium/742/LayoutTests/fast/js/resources@89068',
   'src/chrome/test/data/layout_tests/LayoutTests/platform/chromium-mac/http/tests/workers':
      'http://svn.webkit.org/repository/webkit/branches/chromium/742/LayoutTests/platform/chromium-mac/http/tests/workers@89068',
   'src/chrome/test/data/layout_tests/LayoutTests/http/tests/resources':
      'http://svn.webkit.org/repository/webkit/branches/chromium/742/LayoutTests/http/tests/resources@89068',
   'src/third_party/skia/gpu':
      '/branches/skia/742/gpu@85752',
   'src/chrome/test/data/layout_tests/LayoutTests/http/tests/filesystem':
      'http://svn.webkit.org/repository/webkit/branches/chromium/742/LayoutTests/http/tests/filesystem@89068',
   'src/third_party/safe_browsing/testing':
      'http://google-safe-browsing.googlecode.com/svn/trunk/testing@106',
   'src/third_party/WebKit':
      '/trunk/deps/third_party/WebKit@76115',
   'src/chrome/test/data/layout_tests/LayoutTests/fast/events':
      'http://svn.webkit.org/repository/webkit/branches/chromium/742/LayoutTests/fast/events@89068',
   'src/third_party/bidichecker':
      'http://bidichecker.googlecode.com/svn/trunk/lib@4',
   'src/third_party/ots':
      'http://ots.googlecode.com/svn/trunk@62',
   'src/third_party/WebKit/Source':
      'http://svn.webkit.org/repository/webkit/branches/chromium/742/Source@89068',
   'src/chrome/test/data/layout_tests/LayoutTests/http/tests/workers':
      'http://svn.webkit.org/repository/webkit/branches/chromium/742/LayoutTests/http/tests/workers@89068',
   'src/testing/gmock':
      'http://googlemock.googlecode.com/svn/trunk@374',
   'src/chrome/test/data/extensions/api_test/permissions/nacl_enabled/bin':
      'http://src.chromium.org/native_client/branches/742/src/native_client/tests/prebuilt@5042',
   'src/chrome/test/data/layout_tests/LayoutTests/fast/filesystem/workers':
      'http://svn.webkit.org/repository/webkit/branches/chromium/742/LayoutTests/fast/filesystem/workers@89068',
   'src/tools/gyp':
      'http://gyp.googlecode.com/svn/trunk@912',
   'src/sdch/open-vcdiff':
      'http://open-vcdiff.googlecode.com/svn/trunk@28',
   'src/chrome/test/data/layout_tests/LayoutTests/platform/chromium-win/storage/domstorage':
      'http://svn.webkit.org/repository/webkit/branches/chromium/742/LayoutTests/platform/chromium-win/storage/domstorage@89068',
   'src/tools/page_cycler/acid3':
      '/trunk/deps/page_cycler/acid3@19546',
   'src/chrome/test/data/layout_tests/LayoutTests/fast/filesystem/resources':
      'http://svn.webkit.org/repository/webkit/branches/chromium/742/LayoutTests/fast/filesystem/resources@89068',
   'src/build/util/support':
      '/trunk/deps/support@20411',
   'src/third_party/libjingle/source':
      'http://libjingle.googlecode.com/svn/branches/chrome-sandbox@55',
   'src':
      '/branches/742/src@99363',
   'src/third_party/WebKit/Tools/DumpRenderTree':
      'http://svn.webkit.org/repository/webkit/branches/chromium/742/Tools/DumpRenderTree@89068',
   'src/third_party/hunspell':
      '/trunk/deps/third_party/hunspell@65351',
   'src/chrome/test/data/layout_tests/LayoutTests/http/tests/appcache':
      'http://svn.webkit.org/repository/webkit/branches/chromium/742/LayoutTests/http/tests/appcache@89068',
   'src/testing/gtest':
      'http://googletest.googlecode.com/svn/trunk@560',
   'src/v8':
      'http://v8.googlecode.com/svn/branches/3.2@8988',
   'src/third_party/libvpx':
      '/branches/libvpx/742@83787',
   'src/breakpad/src':
      'http://google-breakpad.googlecode.com/svn/trunk/src@786',
   'chromeos':
      '/trunk/src/tools/cros.DEPS@82298',
   'src/googleurl':
      'http://google-url.googlecode.com/svn/trunk@153',
   'src/third_party/hunspell_dictionaries':
      '/trunk/deps/third_party/hunspell_dictionaries@79099',
   'src/chrome/test/data/layout_tests/LayoutTests/platform/chromium-win/fast/events':
      'http://svn.webkit.org/repository/webkit/branches/chromium/742/LayoutTests/platform/chromium-win/fast/events@89068',
   'src/third_party/leveldb':
      'http://leveldb.googlecode.com/svn/trunk@21',
   'src/third_party/scons-2.0.1':
      'http://src.chromium.org/native_client/branches/742/src/third_party/scons-2.0.1@5042',
   'src/third_party/webdriver/python/selenium':
      'http://selenium.googlecode.com/svn/trunk/py/selenium@11696',
   'src/third_party/speex':
      '/trunk/deps/third_party/speex@70427',
   'src/third_party/libsrtp/src':
      '/trunk/deps/third_party/libsrtp@60080',
   'src/third_party/pylib':
      'http://src.chromium.org/native_client/branches/742/src/third_party/pylib@5042',
   'src/third_party/WebKit/LayoutTests':
      'http://svn.webkit.org/repository/webkit/branches/chromium/742/LayoutTests@89068',
   'src/third_party/snappy/src':
      'http://snappy.googlecode.com/svn/trunk@29',
   'src/chrome/test/data/layout_tests/LayoutTests/http/tests/websocket/tests':
      'http://svn.webkit.org/repository/webkit/branches/chromium/742/LayoutTests/http/tests/websocket/tests@89068',
   'src/chrome/test/data/layout_tests/LayoutTests/media':
      'http://svn.webkit.org/repository/webkit/branches/chromium/742/LayoutTests/media@89068',
   'src/chrome/test/data/layout_tests/LayoutTests/platform/chromium-mac/fast/events':
      'http://svn.webkit.org/repository/webkit/branches/chromium/742/LayoutTests/platform/chromium-mac/fast/events@89068',
   'src/third_party/libjpeg_turbo':
      '/trunk/deps/third_party/libjpeg_turbo@78340',
   'src/chrome/test/data/layout_tests/LayoutTests/platform/chromium-mac/storage/domstorage':
      'http://svn.webkit.org/repository/webkit/branches/chromium/742/LayoutTests/platform/chromium-mac/storage/domstorage@89068',
   'src/third_party/skia/src':
      '/branches/skia/742/src@85754',
   'src/third_party/ffmpeg':
      '/branches/ffmpeg/742/source@83786',
   'src/third_party/cacheinvalidation/files/src/google':
      'http://google-cache-invalidation-api.googlecode.com/svn/trunk/src/google@80',
   'src/chrome/test/data/layout_tests/LayoutTests/platform/chromium-win/fast/workers':
      'http://svn.webkit.org/repository/webkit/branches/chromium/742/LayoutTests/platform/chromium-win/fast/workers@89068',
   'src/third_party/WebKit/Tools/Scripts':
      'http://svn.webkit.org/repository/webkit/branches/chromium/742/Tools/Scripts@89068',
   'src/chrome/test/data/layout_tests/LayoutTests/storage/domstorage':
      'http://svn.webkit.org/repository/webkit/branches/chromium/742/LayoutTests/storage/domstorage@89068',
   'src/third_party/icu':
      '/trunk/deps/third_party/icu46@80478',
   'src/seccompsandbox':
      'http://seccompsandbox.googlecode.com/svn/trunk@153',
   'src/third_party/yasm/source/patched-yasm':
      '/trunk/deps/third_party/yasm/patched-yasm@73761',
   'src/chrome/test/data/layout_tests/LayoutTests/platform/chromium-win/http/tests/workers':
      'http://svn.webkit.org/repository/webkit/branches/chromium/742/LayoutTests/platform/chromium-win/http/tests/workers@89068',
   'src/third_party/angle':
      'http://angleproject.googlecode.com/svn/branches/chrome_m12@631',
   'src/third_party/swig/Lib':
      '/trunk/deps/third_party/swig/Lib@69281',
}

skip_child_includes =  ['breakpad', 'chrome_frame', 'native_client', 'o3d', 'pdf', 'sdch', 'skia', 'testing', 'third_party', 'v8'] 

hooks =  [{'action': ['python', 'src/build/gyp_chromium'], 'pattern': '.'}] 

include_rules =  ['+base', '+build', '+ipc', '+unicode', '+testing']